defaults:
  -
    scope:
      path: "nus/*.md"
    values:
      layout: "nus_module_review"
      permalink: "/nus/:basename.html"

include: ["nus"]

url: "https://bernardteo.me"
plugins:
  - jekyll-sitemap
